# Generated by Django 4.0.2 on 2023-01-06 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(default='', max_length=200)),
                ('instructor_email', models.CharField(default='', max_length=200)),
                ('course_number', models.IntegerField(default=0)),
                ('semester_code', models.IntegerField(default=0)),
                ('course_section', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=10)),
                ('catalog_number', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('units', models.CharField(default='', max_length=10)),
                ('component', models.CharField(default='', max_length=10)),
                ('class_capacity', models.IntegerField(default=0)),
                ('wait_list', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('topic', models.CharField(default='', max_length=200)),
                ('meetings_days', models.CharField(default='', max_length=15)),
                ('meetings_start_time', models.SlugField(default='', max_length=10)),
                ('meetings_end_time', models.SlugField(default='', max_length=10)),
                ('facility_description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='classify.Class')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('courses', models.ManyToManyField(to='classify.Class')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classify.profile')),
                ('voted_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=5000)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 1, 6, 20, 48, 49, 286157), verbose_name='date published')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.schedule')),
                ('voted_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
