# Generated by Django 4.0.2 on 2023-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_class_enrl_stat_descr_alter_class_catalog_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='subject',
            field=models.CharField(max_length=7),
        ),
    ]
