# Generated by Django 3.2.4 on 2023-04-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_profile_muted_course_alter_profile_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('passcode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
