# Generated by Django 3.2.4 on 2023-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0009_email_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_attribute',
            field=models.CharField(default='', max_length=100),
        ),
    ]
