# Generated by Django 3.2.4 on 2023-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0010_class_course_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_attribute',
            field=models.CharField(default='', max_length=500),
        ),
    ]
