# Generated by Django 4.0.2 on 2023-01-05 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0018_comment_pub_date_schedule_downs_schedule_ups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 20, 53, 40, 836291), verbose_name='date published'),
        ),
    ]
